
@startuml
left to right direction
actor Customer as C

rectangle "항공권 예약 시스템" {
  rectangle "Ticket Service" {
    usecase "항공권 조회(예약)" as UC1
    usecase "항공편 조회" as UC2
  }

  rectangle "Reservation Service" {
    usecase "예약" as UC3
    usecase "예약 취소" as UC4
    usecase "예약 취소 수수료 계산" as UC5
    usecase "예약 상태 변경" as UC6
    usecase "특별 서비스 선택" as UC7
    usecase "승객 정보 입력" as UC8
    usecase "총 가격 계산" as UC9
  }

  rectangle "Payment Service" {
    usecase "결제 수단 선택" as UC10
    usecase "결제 승인" as UC11
    usecase "결제 실패/취소" as UC12
    usecase "결제 환불" as UC13
  }

  rectangle "Flight Service" {
    usecase "퍼석 배정 취소" as UC14
  }

  rectangle "Ticket Issue" {
    usecase "항공권 발권" as UC15
    usecase "결제 완료 시 자동 발권" as UC16
  }
}

C --> UC1
C --> UC2
C --> UC3
C --> UC4

UC4 ..> UC5 : <<include>>
UC3 ..> UC9 : <<include>>
UC3 ..> UC8 : <<include>>
UC3 ..> UC7 : <<include>>
UC4 ..> UC6 : <<extend>>
UC10 ..> UC11 : <<include>>
UC11 ..> UC15 : <<include>>
UC15 ..> UC16 : <<include>>
UC11 <.. UC12 : <<extend>>

UC3 ..> UC10 : <<include>>
UC4 ..> UC13 : <<include>>
UC14 ..> UC13 : <<include>>
@enduml
